### ISSUE TITLE
Register - No module named services

### ISSUE THREAD

**Issue by pablobfonseca** [dmonn/socialize#4]
I've received this error when I was trying to run `socl register`
![screen shot 2016-10-17 at 5 55 36 pm](https://cloud.githubusercontent.com/assets/5843859/19453214/0f3dc164-9493-11e6-930d-846a6582fd9f.png)

**Comment by dmonn** [comment]
Hello there.

Python3 support was added in the current version 1.0.4 which is available now via [pip](https://pypi.python.org/pypi/socialize).
I also had a problem with the [pip cache](http://stackoverflow.com/questions/9510474/removing-pips-cache) there, so you might need to remove that first.

**Comment by pablobfonseca** [comment]
Working fine here, thanks @dmonn
