### ISSUE TITLE
Failed to create process

### ISSUE THREAD

**Issue by tionis** [dmonn/socialize#9]
Since the update which fixed the **file()** problem everytime I try to execute socialize via the socl command it returns a "failed to create process"

**Comment by dmonn** [comment]
Hey there, this seems to be a common problem with pip on Windows itself, not with this package. Consult [this](https://github.com/pypa/pip/issues/2783) and [this issue.](https://github.com/semio/ddf_utils/issues/38). You'll have to update setuptools.

**Comment by tionis** [comment]
Problem was solved, just follow these steps (originally posted by jheeffer)
Quick manual fix:

    1. Open Scripts/socl-script.py in python install folder
    2. Change first line to have quotes around path
    E.g.
    #!c:\program files (x86)\python35-32\python.exe
    to
    #!"c:\program files (x86)\python35-32\python.exe"
    3. run socl
    4. Profit
Thank you @dmonn
